### ISSUE TITLE
how do i change drop time

### ISSUE THREAD

**Issue by UncreativeBrain** [Lexa307/DiscordCardBot#11]
how do i change drop time from 24 hours to 1 hour?
как мне поменять время дропа с 24 часов до  1 часа?

**Comment by Lexa307** [comment]
@UncreativeBrain На данный момент это можно сделать так:
1) Убедитесь что в файле .env **RESET_LOCAL_TIME = ""**
2)В файле commands/DropCard.js 
объявите переменную в начале `const RESETTIME = 1000 * 3600 * 1 ` где 1 - количество нужных вам часов по истечению которых можно будет повторно использовать команду drop
далее
в функции **daysDiff** поменяйте строчку где идет подсчет переменной **daysDiff** 
`let daysDiff = diffTime / (RESETTIME); `

Для корректного отображения количества времени, которое осталось для повторного использования команды drop
в DropCard.js найдите строчку
`lastDropDate.setDate(lastDropDate.getDate() + 1);`
и замените ее на:
`lastDropDate.setMilliseconds(RESETTIME);`
