### ISSUE TITLE
Draw cards for other people

### ISSUE THREAD

**Issue by Anonmusus** [Lexa307/DiscordCardBot#2]
Add a command that lets you draw a card for the user you mentioned. It could be gatekept behind a specific role to prevent possible abuse.

**Comment by Lexa307** [comment]
Hi, can i get more info about that feauture?
How should it be work? Like someone with "specific role" can use **pokajimne** with mention of another user?
Or maybe it wold be like adding a new card to a database for person? Or something else...

**Comment by Anonmusus** [comment]
For example, "!newcommand @Otheruser" would add a new card to the database for @Otheruser. And only people with a specified role can use it. I think it's better if it's a separate command than pokajimne, because it's more flexible to not have it linked to the pokajimne timer.

**Comment by Lexa307** [comment]
I'm sorry that I haven't updated the bot for so long, now this function is available to the admin using the **givecard** command in English localization
